### ISSUE TITLE
Readme Specifies run command that doesn't work

### ISSUE THREAD

**Issue by benofben** [neo4j-documentation/labs-pages#66]
It looks like the readme suggests a "npm run dev" command that doesn't have a supporting script.
![image](https://github.com/neo4j-documentation/labs-pages/assets/8282917/6ea0315e-c36b-4f81-89a6-687915f068e9)

**Comment by benofben** [comment]
It looks like this should probably be the npm start command instead of npm dev.

**Comment by jexp** [comment]
Fixed
